### ISSUE TITLE
Newline after the modified mapping field breaks the output format

### ISSUE THREAD

**Issue by semihbkgr** [semihbkgr/yamldiff#38]
left.yaml
```yaml
item:
  name: name
  description: description
```

right.yaml
```yaml
item: name
```

```bash
$ yamldiff left.yaml right.yaml
~ .item:
    name: name
    description: description
    ↓
    name
```

putting extra newline after the `item` field (which makes the yaml unformatted) breaks the indent level in the output

left.yaml
```yaml
item:

  name: name
  description: description
```

```bash
$ yamldiff left.yaml right.yaml
~ .item:

      name: name
      description: description
    ↓
    name
```
